name: Python CI

on:
  push:
    branches:
      - master  # Trigger this workflow on push to the master branch
  pull_request:
    branches:
      - master  # Trigger this workflow for pull requests to the master branch

jobs:
  test:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use Python 3.8 (you can adjust the version if needed)

      - name: Install dependencies (optional)
        run: |
          # You can add any additional installations here if needed
          echo "No requirements.txt, skipping dependencies installation"

      - name: Run Python script
        run: |
          python testFile.py  # Replace with the name of your Python script
